use_frameworks!
platform :ios, '9.0'

target 'ReactiveKitSwappableDatasource_Example' do
  pod 'ReactiveKitSwappableDatasource/Realm', :path => '../'

  target 'ReactiveKitSwappableDatasource_Tests' do
    inherit! :search_paths
    pod 'Nimble'

  end
end
